# Generated by Django 5.0.4 on 2024-05-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
    ]
