# Generated by Django 5.0.4 on 2024-05-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('course_name', models.CharField(max_length=100)),
                ('hole_1', models.IntegerField(default=0)),
                ('hole_2', models.IntegerField(default=0)),
                ('hole_18', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
