# Generated by Django 5.0.4 on 2024-05-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_golfscore_delete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfscore',
            name='hole_10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_16',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_17',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='golfscore',
            name='hole_9',
            field=models.IntegerField(default=0),
        ),
    ]
